# Generated by Django 5.2 on 2025-04-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_cart_order_orderitem_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("fast_food", "Fast Food"),
                    ("pizza", "Pizza"),
                    ("burger", "Burger"),
                    ("main_course", "Main Course"),
                    ("biryani", "Biryani"),
                    ("curry", "Curry"),
                    ("dessert", "Dessert"),
                    ("beverage", "Beverage"),
                ],
                default="fast_food",
                max_length=20,
            ),
        ),
    ]
