# Generated by Django 5.2 on 2025-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_item_item_image_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="prep_time",
            field=models.CharField(
                blank=True,
                help_text="Preparation time (e.g., '30 minutes', '2 hours')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("fast_food", "Fast Food"),
                    ("main_course", "Main Course"),
                    ("drinks", "Drinks"),
                    ("sweet", "Sweet"),
                ],
                default="fast_food",
                max_length=20,
            ),
        ),
    ]
