# Generated by Django 5.2 on 2025-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_item_prep_time_order_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_time",
            field=models.IntegerField(
                blank=True, help_text="Estimated delivery time in minutes", null=True
            ),
        ),
    ]
