# Generated by Django 5.2 on 2025-04-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_order_estimated_delivery_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="timer_start",
            field=models.DateTimeField(
                blank=True, help_text="When the delivery timer was started", null=True
            ),
        ),
    ]
